package BaekJoon;

public class Main{
    public static void main(String[] args) throws Exception{
    	System.out.println("#1 YES\r\n" + 
    			"#2 NO\r\n" + 
    			"#3 YES\r\n" + 
    			"#4 YES\r\n" + 
    			"#5 YES\r\n" + 
    			"#6 YES\r\n" + 
    			"#7 NO\r\n" + 
    			"#8 NO\r\n" + 
    			"#9 YES\r\n" + 
    			"#10 YES\r\n" + 
    			"#11 YES\r\n" + 
    			"#12 YES\r\n" + 
    			"#13 YES\r\n" + 
    			"#14 NO\r\n" + 
    			"#15 YES\r\n" + 
    			"#16 YES\r\n" + 
    			"#17 YES\r\n" + 
    			"#18 YES\r\n" + 
    			"#19 YES\r\n" + 
    			"#20 YES\r\n" + 
    			"#21 YES\r\n" + 
    			"#22 YES\r\n" + 
    			"#23 YES\r\n" + 
    			"#24 YES\r\n" + 
    			"#25 YES\r\n" + 
    			"#26 YES\r\n" + 
    			"#27 YES\r\n" + 
    			"#28 YES\r\n" + 
    			"#29 YES\r\n" + 
    			"#30 YES\r\n" + 
    			"#31 YES\r\n" + 
    			"#32 YES\r\n" + 
    			"#33 YES\r\n" + 
    			"#34 YES\r\n" + 
    			"#35 NO\r\n" + 
    			"#36 YES\r\n" + 
    			"#37 YES\r\n" + 
    			"#38 YES\r\n" + 
    			"#39 NO\r\n" + 
    			"#40 NO\r\n" + 
    			"#41 YES\r\n" + 
    			"#42 YES\r\n" + 
    			"#43 NO\r\n" + 
    			"#44 YES\r\n" + 
    			"#45 YES\r\n" + 
    			"#46 YES\r\n" + 
    			"#47 YES\r\n" + 
    			"#48 NO\r\n" + 
    			"#49 NO\r\n" + 
    			"#50 YES\r\n" + 
    			"#51 NO\r\n" + 
    			"#52 YES\r\n" + 
    			"#53 YES\r\n" + 
    			"#54 YES\r\n" + 
    			"#55 YES\r\n" + 
    			"#56 YES\r\n" + 
    			"#57 NO\r\n" + 
    			"#58 YES\r\n" + 
    			"#59 YES\r\n" + 
    			"#60 NO\r\n" + 
    			"#61 YES\r\n" + 
    			"#62 YES\r\n" + 
    			"#63 NO\r\n" + 
    			"");
    }
}